version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'

    # Open a new pull request every week, if there are updates available.
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'

    ignore:
      # They shipped a bunch of breaking changes.
      - dependency-name: 'eslint'

    labels:
      - 'enhancement'

    # Create one PR for all production dependencies, and one for all
    # development dependencies. The latter is easier/faster to merge because it
    # usually only affects local development.
    groups:
      production:
        dependency-type: 'production'
      development:
        dependency-type: 'development'
