version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'

    # Open a new pull request every week, if there are updates available.
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'

    ignore:
      # They shipped a bunch of breaking changes.
      - dependency-name: 'eslint'

    labels:
      - 'enhancement'
